import { useLanguage } from "@/contexts/LanguageContext";
import { ArrowLeft } from "lucide-react";
import { useNavigate } from "react-router-dom";

const TermsPage = () => {
  const { t } = useLanguage();
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <div className="sticky top-0 z-10 glass border-b border-border/30 px-4 py-3 flex items-center gap-3">
        <button onClick={() => navigate(-1)} className="text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft className="w-5 h-5" />
        </button>
        <h1 className="font-serif text-lg text-foreground">Terms of Service & EULA</h1>
      </div>

      <div className="px-5 py-6 max-w-lg mx-auto space-y-6 text-sm text-muted-foreground leading-relaxed">
        <section className="space-y-2">
          <h2 className="font-serif text-base text-foreground">1. Nature of Service</h2>
          <p>
            AstroChat provides astrological insights based on AI algorithms. These insights are for entertainment purposes only and should not be used as professional financial, legal, or medical advice.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-serif text-base text-foreground">2. Subscriptions</h2>
          <p>
            AstroChat offers a 3-day Free Trial. After the trial ends, a recurring subscription fee will be charged via your App Store / Google Play account.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-serif text-base text-foreground">3. Cancellation</h2>
          <p>
            You may cancel your subscription at any time through your device's subscription settings (App Store or Google Play Store).
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-serif text-base text-foreground">4. User Conduct</h2>
          <p>
            Users must provide accurate birth data for the best experience. Misuse of the platform or abusive behaviour may result in account termination.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-serif text-base text-foreground">5. Limitation of Liability</h2>
          <p>
            AstroChat is not responsible for decisions made based on the app's content. All astrological readings are generated by AI and are intended purely for entertainment and self-reflection.
          </p>
        </section>
      </div>
    </div>
  );
};

export default TermsPage;
